name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run
        env:
          CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASE_URL }}
          CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
          CYPRESS_USER_PASSWORD: ${{ secrets.CYPRESS_USER_PASSWORD }}
          CYPRESS_USER_FIRSTNAME: ${{ secrets.CYPRESS_USER_FIRSTNAME }}
          CYPRESS_USER_LASTNAME: ${{ secrets.CYPRESS_USER_LASTNAME }}
          CYPRESS_USER_POSTAL_CODE: ${{ secrets.CYPRESS_USER_POSTAL_CODE }}
